Sprint 1/step 2
an3wers/react-burger pull request #1
Opened 2023-11-24 16:04 UTC by an3wers

2023-11-24 17:54 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Хорошая работа с `propTypes`

Необходимо исправить:
- Добавьте проверку успешности запроса

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-24 17:54 UTC, andryxxa93 commented on src/api/ingredients.api.js
> +  const response = await fetch(baseApi + endPoint);
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-11-24 17:54 UTC, andryxxa93 commented on src/components/burger/burger-ingredients/burger-ingredients.jsx
> +        <Tab
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2023-11-24 17:54 UTC, andryxxa93 commented on src/components/modal/app-modal.jsx
> +          <div className={styles.header}>
**Можно лучше**
Количество `div` можно уменьшить

2023-11-24 17:54 UTC, andryxxa93 commented on src/utlils/types/ingredients.type.js
> +  _id: PropTypes.string,
**Можно лучше**
У полей ингредиента так же нужно выставлять свойство `isRequired`

2023-11-25 11:41 UTC, an3wers commented on src/api/ingredients.api.js
> +  const response = await fetch(baseApi + endPoint);
Спасибо за рекомендацию, добавил обработку для ошибки. Вынес функцию в утилиты, написал немного по-своему, для того чтобы корректно передать message ошибки в компонент.

2023-11-25 11:41 UTC, an3wers commented on src/utlils/types/ingredients.type.js
> +  _id: PropTypes.string,
Добавил isRequired

2023-11-25 11:42 UTC, an3wers commented on src/components/burger/burger-ingredients/burger-ingredients.jsx
> +        <Tab
В текущих правках пока не стал реализовывать, но по ходу проекта добавлю функционал к табам.

2023-11-26 19:23 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-11-27 05:23 UTC, merged